name: Validate Commit Messages

on:
    workflow_call:

jobs:
    validate_commits:
        runs-on: ubuntu-latest
        steps:
            -   name: Get PR Commits
                id: 'get-pr-commits'
                uses: tim-actions/get-pr-commits@master
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
            -   name: Check if Jira Ticket number is in commit
                uses: tim-actions/commit-message-checker-with-regex@v0.3.1
                with:
                    commits: ${{ steps.get-pr-commits.outputs.commits }}
                    pattern: '^.[A-Z]+-[0-9]+\s[\w| ]+$'
                    error: 'Jira ticket number is required in commit'
