on:
    workflow_call:
        inputs:
            publish:
                type: boolean
                default: false
                required: false
                description: "Determine wether or not we want to publish the NPM package."

permissions:
    contents: read
    packages: write
    actions: read

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Add HTTP basic auth credentials
                run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json
            -   name: Install dependencies
                uses: php-actions/composer@v6
                with:
                    php_version: "8.0"
                    php_extensions: calendar
            -   name: Remove auth.json file
                run: rm -f $GITHUB_WORKSPACE/auth.json
            -   name: "Check file existence"
                uses: andstor/file-existence-action@v1
                with:
                    files: "phpunit.xml.dist"
                    allow_failure: false
            -   name: PHPUnit Tests
                if: steps.check_files.outputs.files_exists == 'true'
                uses: php-actions/phpunit@v3
                env:
                    XDEBUG_MODE: coverage
                with:
                    php_extensions: xdebug calendar
                    bootstrap: vendor/autoload.php
                    configuration: phpunit.xml.dist
                    args: --coverage-text
                    php_version: "8.0"

    publish:
        if: inputs.publish
        needs: build-and-test
        runs-on: ubuntu-latest
        steps:
            -   name: Synchronize Repman
                uses: joelwmale/webhook-action@master
                with:
                    url: ${{ secrets.REPMAN_WEBHOOK }}
