name: Tag next release

on:
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest

        if: github.event.pull_request.merged

        steps:
            -   name: Tag
                uses: K-Phoen/semver-release-action@master
                with:
                    release_branch: main
                    release_strategy: tag
                env:
                    GITHUB_TOKEN: ${{ secrets.ACTION_ACCESS_TOKEN }}
