name: Tag next release

on:
    workflow_call:

jobs:
    semver:
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged
        outputs:
            tag: ${{ steps.semver.outputs.tag }}
        steps:
            -   name: Tag
                id: semver
                uses: K-Phoen/semver-release-action@master
                with:
                    release_branch: main
                    release_strategy: none
                env:
                    GITHUB_TOKEN: ${{ secrets.ACTION_ACCESS_TOKEN }}
    composer_version:
        runs-on: ubuntu-latest
        needs: semver
        if: startsWith(github.event.repository.name, 'php-')
        steps:
            -   uses: actions/checkout@v2
                with:
                    ref: ${{ github.head_ref }}
            -   name: Push tag
                uses: actions-ecosystem/action-push-tag@v1
                with:
                    tag: ${{ needs.semver.outputs.tag }}
                    message: '${{ needs.semver.outputs.tag }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
    npm_version:
        runs-on: ubuntu-latest
        needs: semver
        if: startsWith(github.event.repository.name, 'ts-')
        steps:
            -   uses: actions/checkout@v2
                with:
                    ref: ${{ github.head_ref }}
            -   name: 'change version'
                uses: reedyuk/npm-version@1.1.1
                with:
                    version: ${{ needs.semver.outputs.tag }}
                    git-tag-version: true
