name: Tag next release

on:
    workflow_call:

jobs:
    semver:
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged
        outputs:
            tag: ${{ steps.semver.outputs.tag }}
        steps:
            -   name: Tag
                id: semver
                uses: K-Phoen/semver-release-action@master
                with:
                    release_branch: main
                    release_strategy: tag
                env:
                    GITHUB_TOKEN: ${{ secrets.ACTION_ACCESS_TOKEN }}
    update_package:
        runs-on: ubuntu-latest
        needs: semver
        if: startsWith(github.event.repository.name, 'ts-')
        steps:
            -   uses: actions/checkout@v2
                with:
                    ref: ${{ github.head_ref }}
            -   name: Update package.json
                uses: jossef/action-set-json-field@v2
                with:
                    file: package.json
                    field: version
                    value: ${{ needs.semver.outputs.tag }}
            -   uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: Bump version
