name: Deploy Symfony to Artifactory

on:
    workflow_call:
        inputs:
            slackChannel:
                type: string
                required: false
                default: team-dart-builds
            composerVersion:
                type: string
                required: false
                default: 2.2
            phpExtensions:
                type: string
                required: false
                default: gd xsl zip calendar redis imap intl soap bz2
            artifactoryRepository:
                type: string
                required: false
                default: ${{ github.event.repository.name }}
            artifactPaths:
                type: string
                required: false
                default: 'bin/ config/ docs/ public/ scripts/ src/ templates/ vendor/ composer.json composer.lock VERSION'

jobs:
    notify:
        runs-on: ubuntu-latest
        steps:
            -   name: Slack Notification
                uses: rtCamp/action-slack-notify@v2
                env:
                    SLACK_CHANNEL: ${{ inputs.slackChannel }}
                    SLACK_USERNAME: 'BerryBot'
                    SLACK_ICON: 'https://cdn-icons-png.flaticon.com/512/1514/1514967.png'
                    SLACK_MESSAGE: 'Ja Nick.. Dan krijg je hier wel weer leuke opmerkingen'
                    SLACK_COLOR: '#2196f3'
                    SLACK_TITLE: '`${{ github.event.repository.name }}` has started Artifactory deployment'
                    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    build:
        runs-on: ubuntu-latest
        needs: notify
        steps:
            -   uses: actions/checkout@v3
            -   name: Make sure files and folders have correct rights
                run: |
                    chmod +x bin/console
                    mkdir var && chmod g+w var
            -   name: Add HTTP basic auth credentials
                run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json
            -   id: supported-versions-matrix
                uses: WyriHaximus/github-action-composer-php-versions-in-range@v1
            -   name: Install dependencies
                uses: php-actions/composer@v6
                with:
                    php_version: ${{ steps.supported-versions-matrix.outputs.lowest}}
                    php_extensions: ${{ inputs.phpExtensions }}
                    version: ${{ inputs.composerVersion }}
            -   name: Slack Notification
                if: failure()
                uses: rtCamp/action-slack-notify@v2
                env:
                    SLACK_CHANNEL: ${{ inputs.slackChannel }}
                    SLACK_USERNAME: 'BerryBot'
                    SLACK_ICON: 'https://cdn-icons-png.flaticon.com/512/1514/1514967.png'
                    SLACK_MESSAGE: 'Helaas Nick...'
                    SLACK_COLOR: '#ff5252'
                    SLACK_TITLE: 'Failed installing composer dependencies and assets of `${{ github.event.repository.name }}`'
                    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            -   name: Remove auth.json file
                run: rm -f $GITHUB_WORKSPACE/auth.json
            -   name: Compress workspace
                run: tar -zcf /tmp/vivid-env.tar.gz .
            -   name: Upload workspace
                uses: actions/upload-artifact@v3
                with:
                    name: workspace
                    path: /tmp/vivid-env.tar.gz
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   name: Download artifacts
                uses: actions/download-artifact@v3
                with:
                    name: workspace
                    path: /tmp
            -   name: Extract workspace
                run: |
                    tar -xf /tmp/vivid-env.tar.gz -C ./
            -   name: Get tag
                id: vars
                run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
            -   uses: jfrog/setup-jfrog-cli@v3
                env:
                    JF_URL: ${{ secrets.ARTIFACTORY_URL }}
                    JF_USER: ${{ secrets.ARTIFACTORY_USER }}
                    JF_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
                with:
                    version: 1.54.1
            -   name: Create VERSION file
                run: |
                    echo ${{ steps.vars.outputs.tag }} > VERSION
            -   name: Archive Release
                uses: thedoctor0/zip-release@main
                with:
                    type: 'zip'
                    filename: 'release.zip'
            -   uses: vimtor/action-zip@v1
                with:
                    files: ${{ inputs.artifactPaths }}
                    dest: release.zip
            -   name: Upload to artifactory
                run: |
                    jf rt u "release.zip" "${{ inputs.artifactoryRepository }}/${{ github.event.repository.name }}-${{ steps.vars.outputs.tag }}.zip" --props="Version=${{ steps.vars.outputs.tag }}"
            -   name: Slack Notification
                if: success()
                uses: rtCamp/action-slack-notify@v2
                env:
                    SLACK_CHANNEL: ${{ inputs.slackChannel }}
                    SLACK_USERNAME: 'BerryBot'
                    SLACK_ICON: 'https://cdn-icons-png.flaticon.com/512/1514/1514967.png'
                    SLACK_FOOTER: 'Please close any Zendesk ticket that was fixed in this deployment'
                    SLACK_MESSAGE: 'Ja Nick.. Dan krijg je hier wel weer leuke opmerkingen'
                    SLACK_COLOR: 'good'
                    SLACK_TITLE: 'Created artifactory artifact for `${{ github.event.repository.name }}` with name `${{ inputs.artifactoryRepository }}/${{ github.event.repository.name }}-${{ steps.vars.outputs.tag }}.zip`'
                    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            -   name: Slack Notification
                if: failure()
                uses: rtCamp/action-slack-notify@v2
                env:
                    SLACK_CHANNEL: ${{ inputs.slackChannel }}
                    SLACK_USERNAME: 'BerryBot'
                    SLACK_ICON: 'https://cdn-icons-png.flaticon.com/512/1514/1514967.png'
                    SLACK_FOOTER: ' '
                    SLACK_MESSAGE: 'Ja Nick.. Dan krijg je hier wel weer leuke opmerkingen'
                    SLACK_COLOR: '#ff5252'
                    SLACK_TITLE: 'Failed creating artifactory artifact for `${{ github.event.repository.name }}`'
                    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
