name: Deploy windows Vue

on:
    workflow_call:
        inputs:
            slackChannel:
                type: string
                required: false
                default: team-dart-builds
            composerVersion:
                type: string
                required: false
                default: 2.2
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Make sure files and folders have correct rights
                run: |
                    chmod +x bin/console
                    mkdir var && chmod g+w var
            -   name: Checkout ansible
                uses: actions/checkout@v3
                with:
                    repository: bakerware/ansible-playbooks
                    ref: main
                    token: ${{ secrets.ACTION_ACCESS_TOKEN }}
                    path: ansible/playbook
            -   name: Add HTTP basic auth credentials
                run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json
            -   id: supported-versions-matrix
                uses: WyriHaximus/github-action-composer-php-versions-in-range@v1
            -   name: Install dependencies
                uses: php-actions/composer@v6
                with:
                    php_version: ${{ steps.supported-versions-matrix.outputs.lowest}}
                    php_extensions: gd xsl zip calendar redis imap intl soap bz2
                    version: ${{ inputs.composerVersion }}
            -   name: Remove auth.json file
                run: rm -f $GITHUB_WORKSPACE/auth.json
            -   name: Compress workspace
                run: tar -zcf /tmp/vivid-env.tar.gz .
            -   name: Upload workspace
                uses: actions/upload-artifact@v3
                with:
                    name: workspace
                    path: /tmp/vivid-env.tar.gz
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   name: Download artifacts
                uses: actions/download-artifact@v3
                with:
                    name: workspace
                    path: /tmp
            -   name: Extract workspace
                run: |
                    tar -xf /tmp/vivid-env.tar.gz -C ./
            -   name: Deploy
                uses: rfreij/ansible-playbook-docker-action@master
                with:
                    playbookName: "ansible/playbook/symfony/playbook.yml"
                    inventoryFile: "ansible/inventories/${{ github.event.inputs.environment }}/hosts.yml"
                    keyFileVaultPass: ${{secrets.ANSIBLE_VAULT_PASSWORD}}
                    extraVars: "-e ansible_user=${{secrets.ANSIBLE_USER}} -e ansible_password=${{secrets.ANSIBLE_PASSWORD}}"
                    verbosity: "vv"
            -   name: Slack Notification
                uses: rtCamp/action-slack-notify@v2
                env:
                    SLACK_CHANNEL: ${{ inputs.slackChannel }}
                    SLACK_USERNAME: 'BerryBot'
                    SLACK_ICON: 'https://cdn-icons-png.flaticon.com/512/1514/1514967.png'
                    SLACK_FOOTER: "Please close any Zendesk ticket that was fixed in this deployment"
                    SLACK_MESSAGE: "Ja Nick."
                    SLACK_COLOR: 'good'
                    SLACK_TITLE: "Environment ${{ github.event.inputs.environment }} of ${{ github.event.repository.name }} Has been deployed"
                    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
