name: NPM Package

on:
    push:
        tags:
            - "*"
        branches:
            - main
            - master
    pull_request:
        types: [opened, synchronize, reopened]
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://npm.pkg.github.com/
            - name: npm install and build
              run: |
                  npm config set @bakerware:registry  https://npm.pkg.github.com
                  npm config set //npm.pkg.github.com/:_authToken "${{ secrets.ACTION_ACCESS_TOKEN }}"
                  npm ci
                  npm run build
            - name: Archive production artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: build
                  path: |
                      dist
                      !dist/**/*.md
    publish:
        if: github.event.ref_type == 'tag'
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://npm.pkg.github.com/
            - name: Download build artifact
              uses: actions/download-artifact@v3
              with:
                  name: build
            - run: cd build
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
