name: NPM Package

on:
    workflow_call:
        inputs:
            publish:
                type: boolean
                default: false
                required: false
                description: "Determine wether or not we want to publish the NPM package."

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3
            -   uses: actions/setup-node@v3
                with:
                    node-version: 16
                    registry-url: https://npm.pkg.github.com
            -   name: npm install and build
                run: |
                    npm config set @bakerware:registry  https://npm.pkg.github.com
                    npm config set //npm.pkg.github.com/:_authToken "${{ secrets.ACTION_ACCESS_TOKEN }}"
                    npm ci
                    npm run build
            -   name: Archive production artifacts
                uses: actions/upload-artifact@v3
                with:
                    name: build
                    path: |
                        package.json
                        package-lock.json
                        index.d.ts
                        dist
                        types
                        !dist/**/*.md
    publish:
        if: inputs.publish
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/setup-node@v3
                with:
                    node-version: 16
                    registry-url: https://npm.pkg.github.com
            -   name: Download build artifact
                uses: actions/download-artifact@v3
                with:
                    name: build
            -   name: Get package info
                id: package
                uses: codex-team/action-nodejs-package-info@v1
            -   run: npm publish
                env:
                    NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
            -   name: Slack Notification
                uses: rtCamp/action-slack-notify@v2
                env:
                    SLACK_CHANNEL: 'github'
                    SLACK_USERNAME: 'BerryBot'
                    SLACK_ICON_EMOJI: ':60fpsparrot:'
                    SLACK_FOOTER: "Run npm i ${{ steps.package.outputs.name }}@latest to update to this latest version"
                    SLACK_MESSAGE: "Published ${{ steps.package.outputs.version }}" 
                    SLACK_COLOR: 'good' 
                    SLACK_TITLE: "${{ steps.package.outputs.name }} heeft een nieuwe versie" 
                    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
