name: NPM Package

on:
    push:
        tags:
            - "*"
        branches:
            - main
            - master
    pull_request:
        types: [opened, synchronize, reopened]
    workflow_call:

jobs:
    build:
        uses: ./actions/npm-build@main
        secrets: inherit
    publish:
        if: github.event_name == 'release'
        needs: build
        uses: ./.github/workflows/npm-publish.yml
        secrets: inherit
