name: 'Build & Test Symfony Bundle'

on:
    workflow_call:
        inputs:
            symfonyVersionMatrix:
                type: string
                required: true
                description: 'Example [{"version": "5.4.*", "supports": ["8.0", "8.1"], "args": "--prefer-lowest"},{"version": "6.1.*", "supports": ["8.1"], "args": ""}]'
                default: '[]'

jobs:
    php-requirements:
        runs-on: ubuntu-latest
        outputs:
            phpVersions: ${{ steps.php-requirements.outputs.version }}
            phpExtensions: ${{ steps.php-requirements.outputs.extensions }}
        steps:
            -   uses: actions/checkout@v3
            -   id: php-requirements
                uses: WyriHaximus/github-action-composer-php-versions-in-range@v1
    build-and-test:
        needs: php-requirements
        continue-on-error: true
        strategy:
            matrix:
                symfonyVersion: ${{ fromJSON(inputs.symfonyVersionMatrix) }}
                phpVersion: ${{ fromJSON(needs.php-requirements.outputs.phpVersions) }}
        runs-on: ubuntu-latest
        steps:
            -   name: Check if php version is supported
                if: contains(matrix.symfonyVersion.supports, matrix.phpVersion) == false
                run: exit 1
            -   uses: actions/checkout@v3
            -   name: Add HTTP basic auth credentials
                run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json
            -   name: Setup PHP with PECL extension
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.phpVersion }}
                    extensions: ${{ join(fromJSON(needs.php-requirements.outputs.phpExtensions), ' ') }}
            -   name: Run composer commands
                if: matrix.symfonyVersion.args == ''
                run: |
                    composer install
            -   name: Run composer update if args
                if: matrix.symfonyVersion.args != ''
                run: |
                    composer update ${{ matrix.symfonyVersion.args }}
            -   name: Remove auth.json file
                run: rm -f $GITHUB_WORKSPACE/auth.json
            -   name: "Check file existence"
                uses: andstor/file-existence-action@v1
                id: check_files
                with:
                    files: "phpunit.xml.dist"
                    allow_failure: false
            -   name: PHPUnit Tests
                if: steps.check_files.outputs.files_exists == 'true'
                run: composer test:coverage
            -   name: Coverage Report as Comment (Clover)
                if: steps.check_files.outputs.files_exists == 'true' && github.event_name == 'pull_request'
                uses: lucassabreu/comment-coverage-clover@main
                with:
                    file: output/code-coverage/clover.xml
            -   name: Mark as success if not supported
                if: failure() && contains(matrix.symfonyVersion.supports, matrix.phpVersion) == false
                run: exit 0;
