name: Validate Commit Messages

on:
    workflow_call:

jobs:
    validate_commits:
        runs-on: ubuntu-latest
        steps:
            -   uses: Slashgear/action-check-pr-title@v3.0.0
                with:
                    regexp: '[A-Z]+-[0-9]+\s[\w| ]+'
            -   name: Comment on pull request
                if: failure()
                uses: thollander/actions-comment-pull-request@v1
                with:
                    message: |
                        :warning::warning::warning::warning::warning:
                        
                        PULL REQUEST VALIDATION: Pull request title validation failed.
                        
                        Title needs to start with a Jira Ticket Number, for example: WM-1000 Updated ci cd
                    comment_includes: "PULL REQUEST VALIDATION:"
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
