name: Validate Commit Messages

on:
    workflow_call:

jobs:
    validate_commits:
        runs-on: ubuntu-latest
        steps:
            -   uses: Slashgear/action-check-pr-title@v3.0.0
                with:
                    regex: '[A-Z]+-[0-9]+\s[\w| ]+'
